[package]
name = "shtml"
version = "0.2.0"
edition = "2021"
resolver = "2"

[dependencies]
shtml_macros = { path = "shtml_macros" }
itoa = "1.0"
ryu = "1.0"

[features]
chaos = ["shtml_macros/chaos"]
